version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  task-api:
    build: ./java-task-manager
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasksdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  analyzer:
    build: ./python-analyzer
    ports:
      - "8000:8000"

volumes:
  pgdata:
