version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"

  java-task-manager:
    build: ./java-task-manager
    container_name: java-task-manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  python-analyzer:
    build: ./python-analyzer
    container_name: python-analyzer
    ports:
      - "8000:8000"
    depends_on:
      - postgres
